[package]
name = "copycat"
version = "0.1.0"
edition = "2021"
authors = ["Deftu"]

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"

[dependencies.arboard]
version = "3.4.0"
features = ["image-data", "wayland-data-control"]
