name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: macos-latest
          - name: ubuntu-22.04
          - name: windows-latest
    runs-on: ${{ matrix.platform.name }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Linux Cross Compilation
        if: startsWith(matrix.platform.name, 'ubuntu')
        run: |
          echo Updating package list
          sudo apt-get update
          echo Installing aarch64 cross compilation packages
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          echo Installing arm cross compilation packages
          sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build